### ISSUE TITLE
Create Azure SDK Design Guidelines

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk#1]
- [ ] Architectural Guidelines: Versioning, Compatibility, Packaging, Deployment
- [ ] Architectural Guidelines: Code Generation, i.e. relationship to autorest
- [ ] Architectural Guidelines: Authorization
- [ ]  Design Guidelines: Basic API Structure #15
- [ ]  Design Guidelines: Namespace Factoring #14
- [ ]  Design Guidelines: Customization of Networking Stack #17
- [ ]  Design Guidelines: Supporting Cancellations and Timeouts #16 
- [ ]  Design Guidelines: Logging #12
- [ ]  Design Guidelines: Retries #13 
- [ ] Design Guidelines: Telemetry #43

**Comment by KrzysztofCwalina** [comment]
I think all these are done
