### ISSUE TITLE
Standardize our build/release pipelines

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#102]
- [x] Build pipelines should support building all client/data-plane libraries as well as building just one specific library based on a parameter.
- [x] Release pipelines should support releasing all package artifacts from a build or just those specified via parameter.
- [x] Each release should create a tag and release in the github repo corresponding to the sha that was built against.

**Comment by kurtzeborn** [comment]
Closing this epic.  Our pipelines are standardized!  Now we're going to migrate them to universal pipelines, but that's tracked in a different epic.
