### ISSUE TITLE
Release Track 2 SDK Preview 1 for iOS and Android

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk#1039]
| | [Android](https://github.com/Azure/azure-sdk-for-android/issues/187) | [iOS](https://github.com/Azure/azure-sdk-for-ios/issues/209) |
|---|---|---|
| Core | ❌ | ❌ |
| Identity MSAL | ❌ | ✅ |
| Identity SAS provider | ❌ | ❌ |
| Storage upload | ✅ | ✅ |
| Storage download | ✅ | ✅ |
| Storage list | ✅ | ✅ |
| Storage delete | ❌ | ✅ |
| TM upload | ✅ | ✅ |
| TM download | ✅ | ✅ |
| TM Queue Management | ✅ | ✅ |
| TM Persistence | ✅ | ✅ |
| Resolve TODOs / lints | ❌ | ❌ |
| Public API review | ❌ | ✅ |
| API docs | ❌ | ❌ |
| Build system | ❌ | ❌ |
| Release packaging | ❌ | ❌ |
| Test coverage | ❌ | ❌ |
| READMEs | ❌ | ❌ |
| UX study | ➖ | ✅ |
| Blog post | ❌ | ❌ |

Future previews:
- [ ] Android UX study
- [ ] TM Caching
- [ ] TM Aggregate Operations
- [ ] Public API review w/ Arch Board
- [ ] More / better API docs
- [ ] More test coverage
- [ ] Better READMEs
- [ ] Snippets
- [ ] Sample projects
- [ ] EngSys maturity
