### ISSUE TITLE
Pipeline health metrics, improvements, and dashboards

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#1265]
Now that we have a relatively mature engineering system, it's time to start tracking the health of the system in better ways.

- [x] Metrics/dashboard on where pipelines are spending time and using resources/machines.
  - [ ] Alerting based on health metrics we agree on.
- [x] Determine if static balanced schedule is enough or if we need to write an active scheduler based on load
- [x] Track and report pipeline reliability data.  What are the causes of failures beyond test failures?  Can we take action on any of those?
- [x] Take data driven action to improve performance, reliability, and resource usage.

**Comment by mitchdenny** [comment]
The 30,000ft view of how I think we should approach this is that we should build a system that captures signals from the various components of our engineering system (repositories & pipelines predominantly) and store the raw JSON payloads and then process those to fill in gaps, generally enrich the data with more detail and then store it in an easily queryable location. Then put dashboards on top of that.

To date, when I've been creating dashboards I've been writing programs that trawl through Azure DevOps (or GitHub) to extract information as a kind of batch operation. The problem with that is that we know that some things get deleted due to retention and so we never get a perfectly accurate picture.

This approach would capture the data as soon as it is created, enrich it on an ongoing basis and transform it into a normalized form to cope with things like when we might migrate from Azure Pipelines to GitHub Actions (so that way we get continuity of reporting).

**Comment by mitchdenny** [comment]
Thought I would provide an update on how this is going. At the moment I have the Pipeline Witness service up and running staging. It _is not_ collecting agent time and queue time yet but that is amongst the next data elements that will start getting captured.

Right now Pipeline Witness takes live events coming from Azure DevOps (via Webhook Router) and then downloads the completed runs data from Azure DevOps and stores it in a Cosmos DB document. I have a Power BI report which then reads this data (refreshes automatically every 3 hours) which presents the following views over the data (still under construction):

1. Overview (some high level stats, unique pipelines, unique runs, results, agent time, queue time.
2. Reliability, a breakdown of reliability by repo, run type and pipeline.
3. Resources, a break down of resource (agent time) utilization by repo, run type and pipeline.
4. Performance, a break down of performance (wall-time minus queue time) by repo, run type and pipeline.

Between these we should have a pretty good view over a period of time on whether the changes we make result in improvements and where the hotspots are. Because this is in Power BI it only updates every 3 hours which is not sufficient for investigating issues as they happen.

For this reason I'm considering a second data store (Kusto) which stores about 7 days worth of data which we can use for adhoc queries and investigating live issues across the entire engineering system. Any alerts and notifications would probably run of this store. One option I'm considering is whether I can use the AppInsights instance I use for Pipeline Witness for this purpose or whether I need to setup a separate store.

Currently I'm watching telemetry coming back from Pipeline Witness to make sure it is running in a stable fashion before I start ramping up the volume of data it collects.

When the system goes live I'll regularly be dumping the data as I refine what I want to store. As this stabilizes and I understand our query patterns I'll start increasing the retention.

**Comment by mitchdenny** [comment]
@kurtzeborn and @weshaggard I'm working on the dashboards to help me determine whether we are seeing spikes in queuing at certain times of the day. At the moment it looks like we are OK but I'm not 100% sure about my data just yet.

However what I want to try and establish this is some kind of SLA around the acceptable duration of queue time per pipeline run (duration is the sum of queue wait time across all jobs in the run).

I'm thinking that we bucket it. I think anything above 1 minute warrants a look. And anything above 5 minutes probably is outside of acceptable.

**Comment by mitchdenny** [comment]
This chart shows the queuing in seconds (X-axis) by the count of runs (Y-axis), based on what I am seeing here I think the static tuning that Wes did helped:

![image](https://user-images.githubusercontent.com/513398/83372038-874e3f80-a407-11ea-89c5-54aa100c371a.png)

Still take this data as tentative because I'm using a calculation for queuing that hasn't been approved by the pipelines team ... but it does seem to show variable queue times (highest was 78 seconds).

**Comment by mitchdenny** [comment]
I think that I've gotten this to a point from a systems perspective that we are getting what we need. I need to run a few days with the latest classifiers to see what additional ones we need but that will be a continual process of refining classifiers to zero in on issues to understand how often they occur.

I think the next step here is to try and institute a kind of process that uses these reports to make sure we are following up any insights we glean.

**Comment by weshaggard** [comment]
@mitchdenny should we also setup some sort of alerting? Does PowerBI directly support that?

**Comment by weshaggard** [comment]
Reopened because there are still a few open issues attached to this Epic.
