### ISSUE TITLE
EngSys changes for rename of master branch

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk#1447]
This issue/epic is to group together all the changes that will be required across the engineering system when we eventually rename the **master** branch to **main** (or whatever we choose). Some of this work may be able to be done ahead of the transition through use of parameters/variables where other changes will need to be merged simultaneously with when the branch rename occurs. There are still some unknown unknowns but this is the list that I can see so far:

- [x] Change references to **master** in all the ci.yml/test.yml files.
- [x] Search all scripts that have baked in assumptions about **master** branch
- [x] We have some of our archetype templates which switch behaviors based on **master** branch
- [x] Switch all of the pipelines branch defaults to **refs/heads/main**
- [x] [Any updates to Pipeline Generator??](https://github.com/Azure/azure-sdk-tools/issues/1402)
- [ ] Updates to health metrics reports that filter/refer to master
- [ ] Updates to ```resources``` sections in YAML files
- [ ] Should we also be renaming the master branch in azure-sdk-build-tools?
- [x] Code generation configurations (multiple locations)
- [x] Links. We have direct links to things in our master repo in lots of places from our github.io to docs.microsoft.com to blogs to other places. Depending on features we get from git/github we might need to leave the master branch around to preserve these links, at least for now. 
- [x] When we make the switch all active pull requests targeting master will need to be closed and retargeted.
- [x] We will need documentation to help guide folks how to fix their forks and local clones. Also probably helpful to given instructions on how to fix any branches they have work in. 

We are going to need to think through the impact from a servicing perspective too. If we rename, will it break some of our old versions of build pipelines. We'll probably need to maintain a list of common issues when we do servicing so folks can get the pipelines up and running again when servicing is required.

What did I miss?

**Comment by NullMDR** [comment]
SDK Automation config should be updated from our side.

**Comment by weshaggard** [comment]
Other things that will be broken:

- [ ] Links. We have direct links to things in our master repo in lots of places from our github.io to docs.microsoft.com to blogs to other places. Depending on features we get from git/github we might need to leave the master branch around to preserve these links, at least for now. 
- [ ] When we make the switch all active pull requests targeting master will need to be closed and retargeted.
- [ ] We will need documentation to help guide folks how to fix their forks and local clones. Also probably helpful to given instructions on how to fix any branches they have work in.

**Comment by mitchdenny** [comment]
Thanks Wes.

**Comment by NullMDR** [comment]
I guess we will have some time with main and master exist together if github/git don't have anything to help. In that case maybe we should have a list of things to do in order.

**Comment by mitchdenny** [comment]
I think that having main and master co-exist for a period of time might be a really good approach. Perhaps we could have a model where we continue getting everyone committing to ```refs/heads/master``` but then repoint ```refs/heads/main``` to the latest master in automated way. Then we start transitioning all of our automation to work off ```refs/heads/main``` ... such as live test runs and other tooling like pipeline generator etc.

/cc @weshaggard thoughts on this approach?

**Comment by weshaggard** [comment]
I definitely think that would be a reasonable approach that we would likely need to take. However I'd like to not do any movement until the larger git and/or github decision is made and designed/implemented as the last thing we want to do is move twice because they ended up with a different design.

**Comment by mitchdenny** [comment]
Agreed. Holding pattern for now until we see the fruits of the work that GitHub is doing.

**Comment by mitchdenny** [comment]
GitHub has put out their guidance: https://github.com/github/renaming

There is also some internal 1ES guidance which I won't link here. Its not super urgent, but is important so I'll read through the material that has now been provided and see how that impacts our list above.

**Comment by sima-zhu** [comment]
Have a pipeline to find all occurrences of `master`. https://dev.azure.com/azure-sdk/playground/_build/results?buildId=732192&view=results

It is currently scanning azure-sdk-tools repo. Able to scan other repos by changing the Clone repo step.

**Comment by sima-zhu** [comment]
[Master branch impact analysis](https://microsoft-my.sharepoint.com/:x:/p/sizhu/EUQ_hxC180FFrRHLcygOKRwBird8Q-Mrs8GIU4OqvDbXvw?e=wQoQyX)

**Comment by mitchdenny** [comment]
One thing that I thought of was that we possibly have quite a few links that point to master out there in the wild. We need to figure out whether the GitHub rename mechanism creates a synonym for the branch to avoid broken links.

**Comment by mitchdenny** [comment]
Update, looks like GitHub handles the broken link scenario (yay!):

![image](https://user-images.githubusercontent.com/513398/108442287-e5c79080-72aa-11eb-8b77-59723b8b6a4a.png)

Source: https://github.com/github/renaming
