### ISSUE TITLE
Enable VS/Github code spaces in our repositories

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#1714]
The goal of this epic is to create per-language dev containers and transition our engineering system to using them in the following places:
- [ ] Linux pipeline legs are transitioned to using language specific dev container.
- [x] GitHub code spaces set up for each language repo to use appropriate dev container.
  - As of Aug. 2020 we're still on the wait list for enabling code spaces on our repos.
- [x] Make sure these dev containers also work within VSCode

**Comment by weshaggard** [comment]
@mitchdenny started some of this work in .NET with https://github.com/Azure/azure-sdk-for-net/pull/13827
@jongio started some of this work in the azure-sdk repo with https://github.com/Azure/azure-sdk/pull/1600

**Comment by jongio** [comment]
GH codespaces is enabled for users not orgs. @mitchdenny has access.

**Comment by weshaggard** [comment]
I agree we should be caching these images. I created an Azure Container Registry in our EngSys subscription for just that purpose. We have already started the process of building containers for our .NET test container use at https://github.com/Azure/azure-sdk-for-net/blob/master/eng/containers/ci.yml. I expect we can build on this for the other languages as well and start to build a registry of images we can use for various things.

**Comment by mitchdenny** [comment]
For the CodeSpaces images we'll probably need to configure the registry to allow anonymous access (if you haven't already):

https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=portal

Probably something we'll need to keep an eye on bandwidth wise as well.

**Comment by weshaggard** [comment]
I think the link you posted is for storage accounts but point is still true we will need to enable anonymous access to our container registry and we will also have to look at the bandwidth.

**Comment by mitchdenny** [comment]
Doesn't look like ACR has an anonymous access option. However the .NET team (among others) does seem to host images at ```mcr.microsoft.com```. I'm thinking this might be where we need to host our images.

**Comment by mitchdenny** [comment]
We now have Codespaces enabled (config files in each repo) ... Java and Python are in PR but will go in soon. The next thing we need to do is figure out how to roll this out and make sure we have the right bits and pieces for our team per repo. We need to create a script in each repo which is invoked to do any custom tools setup.

**Comment by weshaggard** [comment]
@mitchdenny great to see this moving. Definitely interested in seeing our pipelines also start picking up these containers and using them.

**Comment by mitchdenny** [comment]
Closing this. It looks like we've got container pipeline builds happening in other areas. This was primarily focused on the Codespaces side of things, which is best using the universal container that they provide.
