### ISSUE TITLE
Repo KPIs and hygiene

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#181]
In addition to the SDKs, the product that our team is "shipping" to customers is the repos themselves.  That includes the documentation and samples found in the repos (the ReadMes), coherency of dependencies, repo organization and structure, and the promptness with which we respond to issues and pull requests.

This epic is being opened to track the last point "the promptness with which we respond to issues and pull requests"  To address this we will do (at least) the following:

- [ ] Report/notification when an issue is idle for more than 48 hours
- [ ] Report/notification when a PR is idle for more than 48 hours (auto close after a month)
- [ ] Autotag issues
- [ ] Auto assign PRs
- [ ] Connect service issues to the appropriate service team support channel

**Comment by kurtzeborn** [comment]
This epic is done.
