### ISSUE TITLE
Improve automation around release processes

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#1830]
- [x] Create a simple process to indicate which library we plan to ship when
- [x] Produce a report/web page that lists the next version release for each package we can use for tracking
- [x] Detect when packages have released and automatically gather the release notes from those packages so we can add them to the monthly release note roll-up.
