### ISSUE TITLE
.NET Guidelines: Fill in cross-language gaps in Design page

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#2087]
## Description

For the MQ Guidelines effort, add guidance to design sections where other languages provide guidance.

## Details

This includes:
- [x] Add guidance to [Naming](https://azure.github.io/azure-sdk/dotnet_introduction.html#naming)
- [x] Add guidance to [Conditional Request Methods](https://azure.github.io/azure-sdk/dotnet_introduction.html#conditional-request-methods): added #2154 for this.
- [x] Add guidance to [Model Type Naming](https://azure.github.io/azure-sdk/dotnet_introduction.html#model-type-naming): added #2298 for this.
- [x] Add guidance to [Hierarchical Clients](https://azure.github.io/azure-sdk/dotnet_introduction.html#hierarchical-clients)
- [x] Add guidance to [Common Libraries](https://azure.github.io/azure-sdk/dotnet_introduction.html#common-libraries)
- [x] Add guidance to [Native Code](https://azure.github.io/azure-sdk/dotnet_introduction.html#native-code)
- [x] Add guidance to [Documentation Style](https://azure.github.io/azure-sdk/dotnet_introduction.html#documentation-style): added #2338 for this.
- [x] In section [Service Method Parameters](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-parameters): TODO: There was a discussion here and the guidance was updated within the .NET team and across Java as well.  Update these.
- [x] In section [The Service Client](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-client) TODO: Mention client immutability here?

**Comment by annelo-msft** [comment]
@sameralameer FYI

**Comment by KrzysztofCwalina** [comment]
Fixed by https://github.com/Azure/azure-sdk/pull/2361
