### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#220]
All repos should contain an `.editorconfig` file to help maintain consistent coding style

## Properties
The following [EditorConfig properties](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties) are good candidates for inclusion:

- indent_style
- indent_size
- end_of_line
- charset
- trim_trailing_whitespace
- insert_final_newline

## Tasks
1. Will need to work with each of the repo owners to define how they want these settings in their repo.  

2. Additionally, if any of these settings result in changes to the sources after they are applied, they will need to be merged in as part of the work with this issue.

3. This will need to be aligned with how the management plane generated code is done as well (we don't want to thrash with the style of code that's coming out of the generators).  This may need to be scoped to just the data plan SDKs for example.

## Repos
- [ ] azure-sdk-for-java
- [ ] azure-sdk-for-js
- [ ] azure-sdk-for-node
- [ ] azure-sdk-for-net
- [ ] azure-sdk-for-python
