### ISSUE TITLE
Move private repos from DevOps to GitHub

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#24]
## Tasks
- [X] Create private GitHub repos
- [x] Mirror/Authorize
  - [ ] Mirror private GitHub repos to private DevOps repos (https://github.com/dotnet/arcade/blob/master/Documentation/VSTS/VSTSOnboarding.md)
  OR
  - [x] Authorize private DevOps pipeline to build private GitHub repo
- [x] Import code (https://help.github.com/articles/importing-a-git-repository-using-the-command-line/)
  - [X] dotnet
  - [x] java
  - [X] python
