### ISSUE TITLE
EngSys - Onboard Cognitive vision and voice to the engineering system

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#2574]
We have the goal of onboarding the vision and speech services into the track 2 SDK. The current architecture of the vision and speech SDK contain C/C++ code that can be used directly by C/C++ developers. These same libraries are also called by other languages (e.g. .NET/C#, Java, Python etc) via their various native interop mechanisms.

At the moment the majority of the source code for the speech and vision SDK rest inside internal repositories, and as part of this effort much of this code will be lifted from these internal repositories, adapted to be track 2 compliant and placed in our open source repositories. There are some exceptions such as proprietary components which the new track 2 libraries will depend on as external dependencies.

Additionally some of the existing dependencies of the the vision and speech SDKs have patches which we may not want to support moving forward, or the dependency itself is otherwise not desirable in our existing track 2 SDK. For this reason it may take some time to work through the changes that need to be made to the vision/speech SDKs to socialize them with our approach to library development in the Azure SDK team.

Ultimately we want to be able to produce binaries and headers for the vision/speech services from the ```azure-sdk-for-cpp``` repository and use those binaries to produce APIs in our other language repositories. This is the first time that we will be flowing dependencies between our language repositories, and this requires some engineering system work (in addition to language specific work to support bundling native binary dependencies with packages).

The proposed approach for onboarding the SDK is as follows:

# Engineering System

- [ ] Set-up placeholder vision and speech track 2 libraries in the ```azure-sdk-for-cpp``` repository.
- [ ] Adapt build to produce binaries and header files.
- [ ] Set-up placeholder vision and speech track 2 libraries in each of the language repos (that depend on the native binaries)
- [ ] Automate downloading and packaging of binary dependencies into other language artifacts (e.g. NuGet packages)

# Cognitive/Language team

- [ ] Lift and shift modules of existing vision and speech libraries and expose via track 2 interfaces
- [ ] Remove/resolve dependency issues (e.g. OpenSSL, Azure C Shared Lib)
- [ ] Lift common APIs into Azure Core.

# Known issues

- [ ] OpenSSL
- [ ] Azure Shared C Lib
- [ ] Internal binary dependencies (distributed by Universal Package)

**Comment by kurtzeborn** [comment]
Old.  Out of date.
