### ISSUE TITLE
Measure Quality, Reliability and Community

### ISSUE THREAD

**Issue by maggiepint** [Azure/azure-sdk#279]
The purpose of a robust engineering system is to improve the quality, reliability, and community around a project. To improve, we must first measure.

- [ ] Establish key metrics for quality, reliability and community
- [ ] Create one-stop eng sys team dashboard for at-a-glance consumption of these metrics
- [ ] Refine metrics to include acceptable ranges, processes for drifting out of range
