### ISSUE TITLE
Standardize test pipelines

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk#311]
- [x] Live/functional test runs should have a pipeline per package in each language (similar to what we do for JS currently)
- [x] Dashboard(s) showing test results
  - Service based dashboard(s) showing results across languages
  - Language based dashboard(s) showing all results for each language
- [x] Alerting/notification per service for the libraries teams to know when there are breaks
  - One code owner per language per service
