### ISSUE TITLE
Azure SDK Tracing Nickel Semester (Jul-Dec21)

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk#3202]
## Azure SDK tracing distributed sample app
- [x] .NET app [draft](https://github.com/lmolkova/azuresdk_tracing_demo)
- [x] Java app [draft](https://github.com/lmolkova/azuresdk_tracing_demo)
- [ ] Python app https://github.com/Azure/azure-sdk-for-python/issues/19971
- [x] JS app https://github.com/Azure/azure-sdk-for-js/issues/16603, PR https://github.com/lmolkova/azuresdk_tracing_demo/pull/1
- [ ] Publish on samples, docs and k8s support

## Azure SDK support in .NET OTel

- [x] ~~https://github.com/open-telemetry/opentelemetry-dotnet/issues/2183~~
- [x] https://github.com/Azure/azure-sdk-for-net/issues/16375 - https://github.com/Azure/azure-sdk-for-net/pull/23192

## HTTP telemetry duplication: 
- [x]  Java https://github.com/Azure/azure-sdk-for-java/issues/22272
- [x]  JS
- [ ]  Python

### HTTP span naming: 
HTTP spans have `/path?query` name and OTel spec says it should be [HTTP VERB](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#name)
  - [x] ~~.NET~~ - won't change until conventions are stable (since shipped in stable version already)
  - [x] Java - https://github.com/Azure/azure-sdk-for-java/pull/24954/
  - [x] JS - https://github.com/Azure/azure-sdk-for-js/pull/19838
  - [ ] Python

### x-ms-request-id and x-ms-client-request-id attributes consistency 
  - [x] .NET (`requestId`, `serviceRequestId`)
  - [x] Java (`x-ms-request-id`) https://github.com/Azure/azure-sdk-for-java/pull/24954/
  - [ ] Python (`x-ms-request-id`,  `x-ms-client-request-id`)
  - [x] JS (`requestId`, `serviceRequestId`)

### Investiage OTel policy place in HTTP pipeline (should be per try)
- [x] .NET
- [x] Java - per try: https://github.com/Azure/azure-sdk-for-java/pull/24954/
- [x] JS - https://github.com/Azure/azure-sdk-for-js/issues/18125
- [ ] Python

## Azure SDK span conventions
   - [x] Publish current versioned schemas (including messaging) https://github.com/Azure/azure-sdk/pull/3260
     - [x] write a blog explaining why we have a different one and path going forward
   - [x] Add mapping to common schema 
     - [x] draft: https://github.com/microsoft/common-schema/pull/262

### Misc
 - [x] Java: https://github.com/Azure/azure-sdk-for-java/issues/23035
 - [x] https://github.com/Azure/azure-sdk-for-java/pull/23141

### Cosmos DB (Java): https://github.com/Azure/azure-sdk-for-java/issues/23032
- [x] Allow client spans creation for convenience calls  
- [x] Allow making spans current (to work with OTel auto-instrumentation)
- [x] CosmosDb to use those APIs
   - [x]  investigate OTel Scope usage in reactor https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4159

### Populate tracer information with SDK name and version
To track usage of tracing per SDK, we can leverage Azure Monitor pipelines, if we populate tracer info (currently `Azure-OpenTelemetry`, no version).
- [ ] .NET
- [ ] Java
- [ ] Python
- [x] JS - https://github.com/Azure/azure-sdk-for-js/pull/19734
