### ISSUE TITLE
Enable Security Tools

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#335]
- [x] CredScan - enable in PR validation (that does not include yml changes), CI, and nightly builds
- [x] Policheck - enable in nightly builds
- [x] ComponentGovernance - already enabled.  Investigate breaking releases if CG is flagging high severity failures
- [x] FxCop - security scanning for .Net
- [x] SpotCheck - static analyzer for Java already in place in our eng system.  Need to verify that Java Architect has configured it to detect security issues.
- [ ] BinSkim - enable in our nightly builds

Additional [security tools](https://securitytools.visualstudio.com/InternalOpenSourceSecurityTools/_wiki/wikis/InternalOpenSourceSecurityTools.wiki?pagePath=%2FWelcome%20to%20C%2BE%20Security%20Tools&wikiVersion=GBwikiMaster&pageId=1) to consider. Also see [Security Guidelines](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/1761/Static-Analysis?anchor=**static-analysis-tool-applicability-per-programming--language**) for more info.
