### ISSUE TITLE
Azure SDK Tracing Copper Semester (Jan-Ju22)

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk#3380]
- Strip sensitive data on `http.url`

## Azure Service Bus support in .NET Application Insights
- [x] https://github.com/microsoft/ApplicationInsights-dotnet/issues/2151

### ServiceBus: support settlement calls tracing
 - [x] .NET 
 - [x] Java 
 - [ ] Python
 - [ ] JS

### Event Hubs:  instrument checkpointer call
   - [x] .NET
   - [x] Java 
   - [ ] Python
   - [ ] JS

## Stretch
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/10969
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/9762
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/21686
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/21684
- [ ] https://github.com/Azure/azure-sdk/issues/3319

**Comment by qjoseph** [comment]
Any news about this issue ?
