### ISSUE TITLE
Azure Schema Registry GA 

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#3980]
Rough list of items to check cross-languages:

- [ ] Perf test in the official framework
- [ ] Remove the preamble backward compat
- [ ] Test cross language combination serialization/deserialization
- [ ] Consider wrapping exceptions
- [ ] Log cache growth

**Comment by deyaaeldeen** [comment]
This has been resolved for all languages 🎉
