### ISSUE TITLE
Azure Event Hubs Commitments (April 2022 - September 2022)

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk#3990]
[Azure Event Hubs](https://docs.microsoft.com/azure/event-hubs/event-hubs-about) is a highly scalable publish-subscribe service that can ingest millions of events per second and stream them to multiple consumers. This lets you process and analyze the massive amounts of data produced by your connected devices and applications. 

We have SDKs in .NET, Java, JavaScript and Python that let developers write applications that use Azure Event Hubs. Latest versions of these packages follow the latest [guidelines for writing SDKs for Azure services](https://azure.github.io/azure-sdk/general_introduction.html) with the goal of being  a client library that is developer-friendly, idiomatic to the ecosystem of the respective languages, and as consistent across different languages and platforms as possible.

This issue tracks the work we have planned for this package for the duration of April - September 2022

### New features
- [ ] Initial stable release of the buffered producer _([design](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/design/proposal-event-hub-buffered-producer.md))_
- [ ] Support for AMQP redirects for consumers, producers, and connections _([initial design](https://github.com/Azure/azure-sdk-for-net/issues/10588))_

### Testing improvements
- [ ] Update stress tests to use the new stress testing platform  _([stress test guidelines](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/608/Draft-Stress-Test-App-Guidelines))_
- [ ] Update perf tests to use the perf test framework that will then allow them to be automated 

### Documentation
- [ ] Troubleshooting Guides _([notebook - Microsoft internal](https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/Shared%20Documents/Language%20-%20Java/Azure%20SDK%20-%20Language%20-%20Java/Support.one#Trouble%20Shooting%20Guides&section-id=%7B7ABF4A91-9073-46C6-AD8E-CDABDF4783EF%7D&page-id=%7B7897A4C7-ECC2-4A2C-92CD-C15827FA64A2%7D&end))_

### General improvements
- Fix incoming customer reported issues

**Comment by jsquire** [comment]
Closing in favor of moving to GitHub Projects
