### ISSUE TITLE
Enable Component Governance Dependency Analyzer

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#40]
Component Governance is an internal DevOps feature which scans your code to find all dependencies, and issues reports if dependencies have legal or security issues.  It should be enabled for all packages in all supported languages.  Some of the service SDK teams (e.g. IoT) are already using Component Governance as part of their builds.

## Getting Started
https://aka.ms/cgdemovideo
https://aka.ms/cgdocs
https://aka.ms/cgapidocs

## Work Items
- [x] Enable CG in all repos
- [ ] Ensure team is alerted when CG fails. Failing the build would be best, but may be impossible if CG performs some tasks asynchronously.  Next best would be to pass the build but send email when CG fails.
- [ ] Understand what types of issues CG does and doesn't detect
- [ ] Review existing CG reports for accuract and remaining work

**Comment by scbedd** [comment]
Mike is going to create a few more issues around additional tasks for CG.

**Comment by weshaggard** [comment]
As a follow-up we need to do the following:

1. Understand what CG does and doesn't do
2. Review existing CG reports for accuracy and remaining work
3. Ensure we receive an alert when CG fails

**Comment by weshaggard** [comment]
>Ensure team is alerted when CG fails. Failing the build would be best, but may be impossible if CG performs some tasks asynchronously.  Next best would be to pass the build but send email when CG fails.

There isn't any way currently to fail the build based on CG reports as the detectors are done asynchronously by another service and a lot of time some additional information is needed to evaluate issues. Instead I've setup a weekly alert email that will send email to myself (they don't support email alias but feature request has been sent) and I will monitor the issues.

> Understand what types of issues CG does and doesn't detect

There are a number of different detectors but there are primarily 2. One that detects known security vulnerabilities in dependency components, it uses a service to check names ans versions of dependencies and will flag any dependencies with known issues. The other checks for legal issues around licenses to ensure you are adhering to the licences of the components you are depending on. 

> Review existing CG reports for accuract and remaining work

All the existing components have been reviewed for all repos and any additional licensing information questions have been provided. Everything is currently clean with a handful alerts for the Java repo that I'll be filing separate issues to address.
