### ISSUE TITLE
Release Storage Track 2 Library

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk#480]
## Preview 2
- [x] Java - https://github.com/azure/azure-sdk-for-java/issues/4314
- [x] Python - https://github.com/azure/azure-sdk-for-python/issues/6285
- [x] .Net - https://github.com/azure/azure-sdk-for-net/issues/6863
- [x] TypeScript - https://github.com/azure/azure-sdk-for-js/issues/4225

## Preview 3
- [x] Java - https://github.com/Azure/azure-sdk-for-java/issues/4451
- [x] Python - https://github.com/Azure/azure-sdk-for-python/issues/6380
- [x] .Net - https://github.com/Azure/azure-sdk-for-net/issues/6952
- [x] TypeScript - https://github.com/Azure/azure-sdk-for-js/issues/4252

## Preview 4
- [ ] Java - https://github.com/Azure/azure-sdk-for-java/issues/4714
- [ ] Python - https://github.com/Azure/azure-sdk-for-python/issues/6692
- [ ] .Net - https://github.com/Azure/azure-sdk-for-net/issues/7142
- [ ] TypeScript - https://github.com/Azure/azure-sdk-for-js/issues/4692

## Preview 5
- [ ] Java - https://github.com/Azure/azure-sdk-for-java/issues/5375
- [ ] Python - https://github.com/Azure/azure-sdk-for-python/issues/7270
- [ ] .Net - https://github.com/Azure/azure-sdk-for-net/issues/7613
- [ ] TypeScript - https://github.com/Azure/azure-sdk-for-js/issues/5141
