### ISSUE TITLE
Release Azure.Identity Library Preview 2

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk#495]
This tracks the work for Azure.Identity preview 2

- [x] Investigate other authentication schemes we need to support (user auth, auth from shared token cache)
    - [x] User/password Authentication
    - [x] Interactive Authentication
    - [x] Device Code Authentication

**Comment by joshfree** [comment]
Closing issue tracking Azure.Identity Preview 2 work
