### ISSUE TITLE
Release Distributed Tracing Track 2 Support

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk#501]
**API Design**
- [x] **Preview 2** (HTTP) Spec for Distributed Tracing Produced @johanste 
   - [x] Spec Ready
   - [x] Spec approved by Azure SDK Arch Board
- [x] **Preview 3** (AMQP) Spec for Distributed Tracing Produced @johanste @lmolkova 
   - [x] Spec Ready - https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92#file-minimal_instrumentation-md
   - [x] Spec approved by Azure SDK Arch Board
- [x] **Preview3** OpenTelemetry AMQP support designed @lmolkova 
- [x] **Preview3** Distributed Tracing Plugin Package Name Standardized @johanste 
   - **Azure.Core.Tracing**

**Feature Work**
- [x] **Preview 2** Distributed Tracing Plugin / Context (OpenCensus) created for each language
- [x] **Preview 2** Tracing Context propagated through each HTTP-based Track 2 Library
   - [x] AppConfiguration
   - [x] Azure.Core
   - [x] Azure.Identity
   - [x] KeyVault (Secrets, Keys)
   - [x] Storage (Blobs, Files, Queues)
- [x] **Preview 3** Tracing Context propagated through each Track 2 Library
   - [x] KeyVault (Certificates)
   - [x] EventHubs (amqp)
   - [x] EPH (amqp)
- [x] **Preview 4** OpenTelemetry Packages available for testing by Azure SDK team
   - [x] .NET SDK (**Alpha available**) https://github.com/open-telemetry/opentelemetry-dotnet#versioning
   - [x]  Java SDK (**Alpha available**) https://github.com/open-telemetry/opentelemetry-java
   - [x]  Python SDK (**Alpha available**) https://github.com/open-telemetry/opentelemetry-python#installation
   - [x]  Javascript SDK (**Alpha available**) https://github.com/open-telemetry/opentelemetry-js
- [x] **Preview 5** Azure SDK Distributed Tracing Plugin / Context tested with OpenTelemetry for each language
- [x] **Preview 5** Audit to make sure tracing is consistent across each language

**Documentation**
- [x] **Preview 5** Samples, Snippets, and Documentation completed for Distributed Tracing with Track 2 SDK Previews

**Related**
- [x] Implement Distributed Tracing in Azure SDK for .NET
   - [x] Preview 2 Tracing Epic for .NET: https://github.com/Azure/azure-sdk-for-net/issues/6933
   - [x] Preview 3 Tracing Epic for .NET: https://github.com/Azure/azure-sdk-for-net/issues/7069
   - [x] Preview 4 Tracing Epic for .NET: https://github.com/Azure/azure-sdk-for-net/issues/7070
   - [x] Preview 5 Tracing Epic for .NET: https://github.com/Azure/azure-sdk-for-net/issues/7920
- [x] Implement Distributed Tracing in Azure SDK for Java  
   - [x] Preview 2 Tracing Epic for Java: https://github.com/Azure/azure-sdk-for-java/issues/4433
   - [x] Preview 3 Tracing Epic for Java: https://github.com/Azure/azure-sdk-for-java/issues/4761
   - [x] Preview 4 Tracing Epic for Java: https://github.com/Azure/azure-sdk-for-java/issues/4762
   - [x] Preview 5 Tracing Epic for Java: https://github.com/Azure/azure-sdk-for-java/issues/5684
- [x] Implement Distributed Tracing in Azure SDK for Python
   - [x] Preview 2 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6356
   - [x] Preview 3 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6596
   - [x] Preview 4 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6597
   - [x] Preview 5 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/7604
- [x] Implement Distributed Tracing in Azure SDK for Javascript / Typescript
   - [x] Preview 2 Tracing Epic for JavaScript: https://github.com/Azure/azure-sdk-for-js/issues/4316
   - [x] Preview 3 Tracing Epic for JavaScript: https://github.com/Azure/azure-sdk-for-js/issues/4587
   - [x] Preview 4 Tracing Epic for JavaScript: https://github.com/Azure/azure-sdk-for-js/issues/4588
   - [x] Preview 5 Tracing Epic for JavaScript: https://github.com/Azure/azure-sdk-for-js/issues/5384

**Comment by johanste** [comment]
@lmolova's list of requirements for message based/AMQP services (e.g. EventHubs): https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92#file-minimal_instrumentation-md

**Comment by joshfree** [comment]
Closing as this work stream is complete.
