### ISSUE TITLE
Unified pipelines

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#532]
## Goals
- [x] Have a unified pipeline for each library/language which includes build, test, analyze, and publish
- [x] Update docs to reflect changes
- [x] Clearly document how to create/add libraries into this system for new teams we on-board
  - [x] This will include providing tools to streamline this process

**Comment by mitchdenny** [comment]
Draft documents in the wiki, waiting for feedback on whether someone can follow them but that was the last thing we needed beyond the pipeline generator.

**Comment by kurtzeborn** [comment]
there's still some cleanup to do related to this epic (tracking issues are associated with it).
