### ISSUE TITLE
Release Azure.Identity Track 2 Library

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk#536]
**API Design**
- [x] **Preview 3** Arch Board review of Preview 2 Credential Types
   - [x] Proposal Ready
   - [x] Design approved
- [x] **Preview 3** SharedTokenCacheCredential APIs reviewed and approved by Azure SDK Core Arch Board
   - [x] Proposal Ready
   - [x] Design approved
- [x] **Preview 3** Finalize MSAL dependency strategy with Arch Board
   - [x] Proposal Ready
   - [x] Design approved
- [x] **Preview 4** Review Exception Patterns across languages (@schaabs)
- [x] **Preview 4** Review Authority Host Configuration and ensure consistency across Languages (@schaabs)

**Feature Work**
- [x] **Preview 3** Provide Feedback & File Issues for MSAL Team (ex: Java) and schedule updates
- [x] **Preview 3** Provide Single Sign-On (SSO) Authentication Support with MSAL
   - [x] Verify Shared Token Cache Design works with mainline scenarios (Visual Studio, Powershell, CLI)
- [x] **Preview 4**  Authorization Code Flow support with MSAL https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow
- [x] **Preview 4** Create a combination of Automated and Manual testing (postman, curl, etc documented steps)

**CUT**
- [x] **Preview 4** Design solution for publishing credentials to shared token cache for dev-time experience (@schaabs)
- [x] **Preview 4** Implement solution for publishing credentials to shared token cache
- [x] **Preview 4** Provide On-Behalf-of (OBO) authorization support with MSAL
   - [x] Cross-Language-SDK testing to ensure the Shared Token Cache functions as expected (correct synchronization)
   - [x] Define Positive/Negative/Stress SSO test cases (cross applications, cross browser tabs)

**Related**
- [x] Identity for .NET
   - [x] Preview 5 for .NET https://github.com/Azure/azure-sdk-for-net/issues/7909
   - [x] Preview 4 for .NET https://github.com/Azure/azure-sdk-for-net/issues/7278
   - [x] Preview 3 for .NET https://github.com/Azure/azure-sdk-for-net/issues/7065
   - [x] Preview 2 for .NET https://github.com/Azure/azure-sdk-for-net/issues/6917
   - [x] Preview 1 for .NET https://github.com/Azure/azure-sdk-for-net/issues/6043
- [x] Identity for Java
   - [x] Preview 5 for Java https://github.com/Azure/azure-sdk-for-java/issues/5679
   - [x] Preview 4 for Java https://github.com/Azure/azure-sdk-for-java/issues/4969
   - [x] Preview 3 for Java https://github.com/Azure/azure-sdk-for-java/issues/4753
   - [x] Preview 2 for Java https://github.com/Azure/azure-sdk-for-java/issues/4419
   - [x] Preview 1 for Java https://github.com/Azure/azure-sdk-for-java/issues/3505
- [x] Identity for Python
   - [x] Preview 5 for Python https://github.com/Azure/azure-sdk-for-python/issues/7591
   - [x] Preview 4 for Python https://github.com/Azure/azure-sdk-for-python/issues/6781
   - [x] Preview 3 for Python https://github.com/Azure/azure-sdk-for-python/issues/6591
   - [x] Preview 2 for Python https://github.com/Azure/azure-sdk-for-python/issues/6337
   - [x] Preview 1 for Python https://github.com/Azure/azure-sdk-for-python/issues/5048
- [x] Identity for Javascript/Typescript
   - [x] Preview 5 for Javascript https://github.com/Azure/azure-sdk-for-js/issues/5371
   - [x] Preview 4 for Javascript https://github.com/Azure/azure-sdk-for-js/issues/4755
   - [x] Preview 3 for Javascript https://github.com/Azure/azure-sdk-for-js/issues/4575
   - [x] Preview 2 for Javascript https://github.com/Azure/azure-sdk-for-js/issues/4300
   - [x] Preview 1 for Javascript https://github.com/Azure/azure-sdk-for-js/issues/2650
