### ISSUE TITLE
Integrate samples and smoke tests fully

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#586]
## Goals
- [ ] Update documentation to provide guidelines on how to write samples that plug into the smoke tests
- [ ] Update smoke tests to consume packages produced from our pipelines
- [ ] Run smoke tests and sample builds in unified pipelines
