### ISSUE TITLE
Improve and streamline test coverage/matrix

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#594]
Now that we have basic UT and live test coverage for all track 2 libraries, we want to expand that with the following:
- [ ] Optimize PR Validation (example: don't run all python tests against all 4 versions of python on all OSs)
- [ ] All supported versions of the service for each package
- [ ] Min/Max versions of dependencies for each package
- [ ] Test against various versions of toolsets (Python and JS)
  - Pretty sure we're covered here, but worth looking at to be sure before closing this epic
- [ ] Test against various OS versions
  - Right now we test on Mac, Linux, and Windows.  Do we want to expand that to include multiple versions of each of those?  Other distros of Linux?
