### ISSUE TITLE
GitHub.io vNext plan for docs

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#606]
Currently we have one pipline that runs on a repo and generates all of the refdocs on github.io in one shot.  We had to disable that automatically running because the docs were drifting "foward" beyond what had been released to the public feeds.

# Goals of this Epic
- [x] Every time a library is released we update the refdocs for that library
- [x] This doc generation step should be a stage in the unified pipelines
- [x] [new] store multiple versions of the docs for previously released libraries
- [x] [new] Only have the index of all libraries on github.io and store the specific library ref docs in blob storage
- [x] [new] Generate docs as part of PR Validation or nightly builds for developers to review (if we move this to blob storage, it becomes trivial)

**Comment by kurtzeborn** [comment]
Closing this epic since we are done with our primary goals.  I've moved all "additional" issues into other epics or created new epics to track them.  This is done.
