### ISSUE TITLE
Valid link enforcement in our repos and releases

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#818]
There are several ideas we want to pursue:
- [x] Markdown (readmes, etc.) need to have valid and correct links to the following:
  - [x] Follow guidelines outlined at https://github.com/Azure/azure-sdk/blob/master/docs/policies/README-TEMPLATE.md#link-guidelines.
  - [x] Version less links to docs
  - [x] Version less links to packages
  - [ ] Links need to be relevant in all contexts that they appear in (repo, packages, docs)
- [x] GitHub.io sites that we generate for all repos need:
    - [x] All links validated
    - [x] Index pages use the same URL structure (goal: should match the repo structure)
    - [x] Use the same set of tools and code to generate the index pages.  Language specific tools should still be used to generate the API refs.
    - [ ] Improve the host name for github.io pages hosted in blob storage (use a CNAME) Issues to track this: https://github.com/Azure/azure-sdk/issues/848
- [x] Readme templates need to be updated (they currently have invalid links) and those updates need to be applied to existing readmes
- [ ] All links need to be consistent and predictable

**Comment by kurtzeborn** [comment]
@KarishmaGhiya, this is a great, cross-cutting thing for you to drive.

**Comment by sima-zhu** [comment]
The issues which needed for the Epic have been addressed. Will create separate issues if any feature request raised from SDK lang team. Closed the epic
