### ISSUE TITLE
Track utilization of Azure resources

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#85]
## Goals
- [x] Plumb data to PowerBI
- [x] Dashboard working in PowerBI
- [x] (Parallel track) Get AIRS data permissions working and query-able
