### ISSUE TITLE
Repo documentation standards

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#88]
- [x] Enforce the existence of a ReadMe which follows architecture board standards.
  - [x] Fail the build if it is missing for a library
  - [x] Open issues for missing ReadMes
  - [x] Support enable/disable this per project
- [x] Add telemetry to ReadMe files in GitHub

**Comment by Petermarcu** [comment]
@kurtzeborn can this one be closed?
