### ISSUE TITLE
Track dependencies across SDKs

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#94]
# Goals
- [x] Dependency reports for packages in each language
- [x] Centralized dependency version management for each language
- [x] Validation of ranges of dependency versions

**Comment by kurtzeborn** [comment]
We're tracking dependencies!  Done.
